### PR TITLE
Sphinx: use doc/ref directives for relative links

### PR DESCRIPTION
**Pull request by ryan-lane**
This change adds an option (m2r_parse_relative_links) that'll configure m2r to parse internal links into doc or ref directives. It uses urlparse to determine if a link is internal or not based on whether a scheme is detected. A ref is used if only an anchor is provided, otherwise the change assumes a doc is being linked to.

Change for issue #15.

### CODE REVIEW

**Comment by ryan-lane** [comment]
Based on the way the tests run, I don't think it's going to be possible for me to hit the coverage required. The diff lines that aren't being covered are either 2/3 compat, or are when m2r is called outside of sphinx, which isn't being tested.

**Comment by lorengordon** [comment]
Just ran into this problem, would be great to see this merged!

**Comment by lorengordon** [comment]
@ryan-lane Quick question... was testing this branch and the anchor links do not appear to be working correctly. Well, they may be rendered to an rst ref as coded, but sphinx is having none of it.

```
[foo](#foo)

# foo
```

The doc above generates a warning in sphinx:

```
WARNING: undefined label: foo (if the link has no caption the label must precede a section header)
```

The released version of m2r works fine with this kind of anchor link, so I think this would be a regression. Unless I'm doing something wrong, which is ultimately my "quick question". 😄 Is there a "correct" way to write the markdown such that sphinx will render the ref link properly?

**Comment by ryan-lane** [comment]
@lorengordon hm. that should work. I'll need to take a look.

**Comment by ryan-lane** [comment]
@lorengordon hm. that should work, but I've reproduced your issue. I'll fix that and push it in.

**Comment by mrexodia** [comment]
What is required for this pull request to get merged? I would like to use this feature to get rid of recommonmark...

**Comment by miyakogi** [comment]
I'm sorry for late response.
I merged this PR.
Thank you for your great efforts!

**Comment by ryan-lane** [comment]
Awesome. Thanks for the merge!

**Pull request merged**
